import { CiaContentConfig, CiaPromotionRule } from '../cia-school/cia-content-config';
import {
  ANJ_BIRTHDAY_DISCOUNT,
  ANJ_BIRTHDAY_REGISTRATION_START,
  ANJ_CONTINUATION_PERIODS,
  ANJ_COURSES,
  ANJ_NEW_PROMOTION_PERIODS,
  ANJ_PEAK_SEASON_RANGES,
  ANJ_REGISTRATION_FEE,
  ANJ_ROOMS,
  ANJ_SEASONAL_FEE_PER_WEEK,
  ANJ_SIDA_DISCOUNT_RATE,
} from './anj-pricing';

const promotionBase = (id: string, name: string, sortOrder: number): CiaPromotionRule => ({
  id,
  name,
  description: '',
  enabled: true,
  sortOrder,
  priority: 10 + sortOrder,
  stackable: true,
  newStudentsOnly: false,
  discountType: 'fixed',
  discountValue: 0,
  appliesTo: 'school-total',
  waiveRegistration: false,
  minimumCourseWeeks: 0,
  minimumAccommodationWeeks: 0,
  coverageTarget: 'none',
});

export const createDefaultAnjContentConfig = (): CiaContentConfig => ({
  schemaVersion: 1,
  schoolCode: 'ANJ',
  courses: ANJ_COURSES.map((item, index) => ({
    id: item.id,
    name: item.name,
    courseType: item.type,
    tuition: item.fee4w ?? 0,
    tuition2027: item.fee4w ?? 0,
    feeByWeeks: item.feeByWeeks ? Object.fromEntries(Object.entries(item.feeByWeeks).map(([weeks, amount]) => [weeks, amount ?? 0])) : undefined,
    allowedWeeks: item.allowedWeeks ? [...item.allowedWeeks] : undefined,
    schedule: item.lessons,
    suitable: item.suitable,
    note: item.suitable,
    enabled: true,
    sortOrder: index,
  })),
  rooms: ANJ_ROOMS.map((item, index) => ({
    id: item.id,
    name: item.name,
    label: item.name,
    code: item.id,
    location: '校内',
    group: item.waterGroup,
    fee: item.fee4w,
    priceMode: item.priceMode,
    minOccupancy: item.minOccupancy,
    maxOccupancy: item.maxOccupancy,
    waterFee4w: item.waterFee4w,
    waterGroup: item.waterGroup,
    deposit: item.deposit,
    note: item.note,
    enabled: true,
    sortOrder: index,
  })),
  localFees: [
    { id: 'ssp', name: 'SSP特殊学习许可证', currency: 'PHP', amount: 7800, billingRule: 'once', includeInTotal: true, note: '移民局收取，通常有效6个月；更换学校需要重新办理。', enabled: true, sortOrder: 0 },
    { id: 'ssp-e-card', name: 'SSP-E Card', currency: 'PHP', amount: 4500, billingRule: 'once', includeInTotal: true, note: '入学时与SSP同时办理，只收一次。', enabled: true, sortOrder: 1 },
    { id: 'acr-i-card', name: 'ACR-I Card 外国人身份证', currency: 'PHP', amount: 4000, billingRule: 'first-visa-extension', includeInTotal: true, note: '按所选旅游签证和完整停留日期预估，第一次需要续签时办理；以学校及移民局要求为准。', enabled: true, sortOrder: 2 },
    { id: 'visa-extension', name: '签证续签', currency: 'PHP', amount: 4940, rates: [4940], billingRule: 'visa-extension-schedule', includeInTotal: true, note: '按所选旅游签证及完整停留日期预估，实际以移民局及学校办理为准。', enabled: true, sortOrder: 3 },
    { id: 'books', name: '教材费', currency: 'PHP', amount: 1500, billingRule: 'per-course-period', periodWeeks: 4, rounding: 'proportional', includeInTotal: true, note: '按累计课程周数估算；不同课程所需教材不同，入学后新增教材按实际购买。', enabled: true, sortOrder: 4 },
    { id: 'student-card', name: '学生证', currency: 'PHP', amount: 200, billingRule: 'once', includeInTotal: true, note: '一次性费用。', enabled: true, sortOrder: 5 },
    { id: 'manila-pickup', name: '马尼拉机场接机', currency: 'PHP', amount: 3000, billingRule: 'selected-manila-pickup', includeInTotal: true, note: '学生自由选择；指定周日固定时间团体接机。', enabled: true, sortOrder: 6 },
    { id: 'clark-pickup', name: '克拉克机场接机', currency: 'PHP', amount: 3000, billingRule: 'selected-clark-pickup', includeInTotal: true, note: '学生自由选择；指定周日固定时间团体接机。', enabled: true, sortOrder: 7 },
    { id: 'laundry', name: '洗衣服务', currency: 'PHP', amount: 150, secondaryAmount: 100, secondaryLabel: '只洗或只烘', billingRule: 'optional', includeInTotal: false, note: '洗衣加烘干150比索／7kg／次；只洗或只烘100比索／7kg／次，按实际使用支付。', enabled: true, sortOrder: 8 },
  ],
  quoteSettings: {
    registrationFee: ANJ_REGISTRATION_FEE,
    futurePriceRegistrationStart: '',
    futurePriceArrivalStart: '2027-01-01',
    shortStayRatios: {},
    peakSeasonFeePerWeek: ANJ_SEASONAL_FEE_PER_WEEK,
    peakSeasonRanges: ANJ_PEAK_SEASON_RANGES.map((range, index) => ({ id: `anj-peak-${index + 1}`, ...range, enabled: true })),
    promotions: [
      {
        ...promotionBase('registration-waiver', '思达免注册费', 0),
        description: '通过思达报名，每名学生免收一次性注册费。',
        discountType: 'none',
        waiveRegistration: true,
      },
      ...ANJ_NEW_PROMOTION_PERIODS.map((period, index) => ({
        ...promotionBase(`anj-new-${index + 1}`, period.label, index + 1),
        description: `${period.label}；按入学日及累计课程周匹配固定优惠${period.lowSeasonPerFourWeeks ? `，并每完整4课程周另减${period.lowSeasonPerFourWeeks}美元` : ''}。`,
        ruleKind: 'anj-new-period',
        newStudentsOnly: true,
        discountTiers: Object.fromEntries(Object.entries(period.regularDiscounts).map(([weeks, amount]) => [weeks, amount ?? 0])),
        incrementWeeks: period.lowSeasonPerFourWeeks ? 4 : undefined,
        incrementValue: period.lowSeasonPerFourWeeks || undefined,
        arrivalStart: period.start,
        arrivalEnd: period.end,
      })),
      ...ANJ_CONTINUATION_PERIODS.map((period, index) => ({
        ...promotionBase(`anj-continuation-${index + 1}`, period.label, ANJ_NEW_PROMOTION_PERIODS.length + index + 1),
        description: `${period.label}；按续课新增课程开始日和新增课程周数计算，不与新生优惠叠加。`,
        ruleKind: 'anj-continuation-period',
        stackable: false,
        discountTiers: Object.fromEntries(Object.entries(period.discounts).map(([weeks, amount]) => [weeks, amount ?? 0])),
        arrivalStart: period.start,
        arrivalEnd: period.end,
      })),
      {
        ...promotionBase('anj-birthday', 'A&J生日优惠', 13),
        description: '新生课程不少于4周并提交生日证明；2026按入学季度匹配出生日期尾数，2027起生日月份须与入学月份相同。',
        ruleKind: 'anj-birthday',
        newStudentsOnly: true,
        discountValue: ANJ_BIRTHDAY_DISCOUNT,
        registrationStart: ANJ_BIRTHDAY_REGISTRATION_START,
        minimumCourseWeeks: 4,
      },
      {
        ...promotionBase('sida-discount', '思达95折', 14),
        description: '先扣A&J固定优惠，再对剩余课程费和住宿费按95折计算。',
        discountType: 'percentage',
        discountValue: Math.round((1 - ANJ_SIDA_DISCOUNT_RATE) * 100),
        appliesTo: 'tuition-and-accommodation',
      },
    ],
    localFeeIntro: '学杂费为到校后以比索支付的预估，按每名学生的签证、课程、住宿和接机分别计算；押金与洗衣服务另列，不计入合计。',
    courseTableTitle: 'A&J 2026年课程费 / 4周',
    courseTableNote: '普通课程按4周价列示；TOEIC与IELTS保分班按学校规定的固定周数单独列示。2027入学暂按2026价格估算，须以学校新价目表确认。',
    groupClassNote: '一对一及团体课节数以所选课程说明为准；保证班的入学成绩、出勤与保分条件需另行确认。',
    roomTableTitle: 'A&J 2026年住宿费 / 4周',
    roomTableNote: '每人价与整间总价房型已分别标注；整间总价房型仅在对应人数选择相同房型和日期时计收一次。',
    stayPolicyTitle: 'A&J入住与住宿提醒',
    stayPolicies: [
      { label: '入住日期', value: '周日入住', note: '课程与住宿按周日至周六的完整周计算。' },
      { label: '退房日期', value: '周六退房', note: '延住、提前入住和空房需由顾问向学校确认。' },
      { label: '整间房型', value: '人数与日期必须一致', note: 'Suite、Studio多人入住和Villa独享房型按整间计价，不可按个人重复收费。' },
    ],
    extraNightRates: [],
  },
  quoteImageSettings: {
    paymentSectionTitle: '学校费用明细',
    paymentNotes: { registration: '一次性费用；通过思达报名免收', course: '', accommodation: '', promotion: '' },
    localFeeSectionTitle: '到校后学杂费明细',
    localFeeIntro: '以下为按当前签证、课程、住宿与接机选择计算的比索费用预估，最终以学校和移民局实收为准。',
    localFeeNotes: {},
    serviceSectionTitle: '为什么选择思达启航？',
    benefits: [
      { title: '0中介费', text: '学校合作价格，不额外加收服务费' },
      { title: '价格保护', text: '同条件可比价，核实更低价退差价' },
      { title: '全程报名协助', text: '选校、签证、付款及行前指导' },
      { title: '海外驻点售后', text: '学习期间持续跟进，问题有人协助' },
    ],
    serviceLocations: ['深圳总部', '菲律宾驻点', '欧洲驻点'],
    alumniBenefitTitle: 'A&J优惠提醒',
    alumniBenefitText: '新生、生日、淡季和续课优惠按所选入学日及周数自动匹配；最终资格以学校确认为准。',
    noteSectionTitle: '报价说明',
    footerNotes: [
      '课程和住宿按完整周计算，周日入住、周六退房。',
      '2027价格目前沿用2026价目表预估，公布新价后需重新确认。',
      '人民币金额按参考汇率估算，最终以实际兑换或支付汇率为准。',
      '最终以学校价格、空房、优惠资格、移民局政策及顾问确认结果为准。',
    ],
  },
  media: [],
});

export const cloneAnjContentConfig = (value: CiaContentConfig): CiaContentConfig => {
  const cloned = structuredClone(value);
  if (!cloned.quoteImageSettings.localFeeNotes) cloned.quoteImageSettings.localFeeNotes = {};
  if (!cloned.media) cloned.media = [];
  return cloned;
};
