import { CiaContentConfig, CiaPromotionRule } from '../cia-school/cia-content-config';
import {
  JIC_COURSE_FEES,
  JIC_LOCAL_FEE_COPY,
  JIC_PEAK_FEE_PER_WEEK,
  JIC_PROMOTION_COPY,
  JIC_REGISTRATION_FEE,
  JIC_ROOM_FEES,
} from './jic-pricing';

const promotion = (id: string, name: string, ruleKind: string, sortOrder: number): CiaPromotionRule => ({
  id,
  name,
  ruleKind,
  description: '',
  enabled: true,
  sortOrder,
  priority: 10 + sortOrder,
  stackable: true,
  newStudentsOnly: false,
  discountType: 'fixed',
  discountValue: 0,
  appliesTo: 'school-total',
  waiveRegistration: false,
  minimumCourseWeeks: 4,
  minimumAccommodationWeeks: 0,
  coverageTarget: 'none',
});

const twinAndQuadRoomIds = JIC_ROOM_FEES.filter(room => room.category !== 'single').map(room => room.id);

export const createDefaultJicContentConfig = (): CiaContentConfig => ({
  schemaVersion: 1,
  schoolCode: 'JIC',
  courses: JIC_COURSE_FEES.map((item, index) => ({
    id: item.id,
    name: item.displayName,
    englishName: item.name,
    courseType: item.campus === 'challenger' ? 'Challenger 挑战校区' : 'Premium 高级校区',
    campus: item.campus,
    tuition: item.tuition,
    tuition2027: item.tuition,
    schedule: item.suitable,
    suitable: item.suitable,
    note: item.suitable,
    minimumWeeks: 4,
    allowedWeeks: [4, 6, 8, 12, 16, 20, 24],
    enabled: true,
    sortOrder: index,
  })),
  rooms: JIC_ROOM_FEES.map((item, index) => ({
    id: item.id,
    name: item.name,
    label: item.name,
    code: item.category,
    location: '校内',
    group: item.campus === 'challenger' ? 'Challenger 挑战校区' : 'Premium 高级校区',
    campus: item.campus,
    fee: item.fee,
    single: item.category === 'single',
    note: item.note,
    enabled: true,
    sortOrder: index,
  })),
  localFees: [
    { id: 'ssp', name: 'SSP特殊学习许可证', currency: 'PHP', amount: 7800, billingRule: 'once', includeInTotal: true, note: '移民局收取，按报名学习时长办理；续费及换校需要重新办理。', enabled: true, sortOrder: 0 },
    { id: 'ssp-e-card', name: 'SSP-E CARD', currency: 'PHP', amount: 4500, billingRule: 'once', includeInTotal: true, note: '移民局收取，入学时与SSP同时办理，只收一次。', enabled: true, sortOrder: 1 },
    { id: 'acr-i-card', name: 'ACR-I CARD 外国人身份证', currency: 'PHP', amount: 4000, billingRule: 'first-visa-extension', includeInTotal: true, note: '按所选旅游签证预估，第一次续签时办理，只收一次。', enabled: true, sortOrder: 2 },
    { id: 'maintenance', name: '维护管理费', currency: 'PHP', amount: 1000, billingRule: 'per-accommodation-period', periodWeeks: 4, rounding: 'proportional', includeInTotal: true, note: '校内教学楼及其他设施维护费；超过4周按实际周数比例预估。', enabled: true, sortOrder: 3 },
    { id: 'utilities', name: '水电费', currency: 'PHP', amount: 3000, billingRule: 'per-accommodation-period', periodWeeks: 4, rounding: 'proportional', includeInTotal: true, note: '超过4周按实际周数比例预估。', enabled: true, sortOrder: 4 },
    { id: 'manila-pickup', name: '马尼拉机场接机', currency: 'PHP', amount: 3000, billingRule: 'selected-manila-pickup', includeInTotal: true, note: '自由选择是否需要；周日固定时间团体接机，选择后计入学杂费预估。', enabled: true, sortOrder: 5 },
    { id: 'clark-pickup', name: '克拉克机场接机', currency: 'PHP', amount: 3000, billingRule: 'selected-clark-pickup', includeInTotal: true, note: '自由选择是否需要；周日固定时间团体接机，选择后计入学杂费预估。', enabled: true, sortOrder: 6 },
    { id: 'visa-extension', name: '签证续签', currency: 'PHP', amount: 4940, rates: [4940], billingRule: 'visa-extension-schedule', includeInTotal: true, note: '按所选旅游签证及完整停留跨度预估；每次续签增加30天。', enabled: true, sortOrder: 7 },
    { id: 'books', name: '教材费', currency: 'PHP', amount: 1900, billingRule: 'per-course-period', periodWeeks: 8, rounding: 'ceil', includeInTotal: true, note: '按每套教材约使用8周预估；实际按学习进度购买。', enabled: true, sortOrder: 8 },
    { id: 'student-card', name: '学生证', currency: 'PHP', amount: 200, billingRule: 'once', includeInTotal: true, note: '一次性费用，包含拍摄照片。', enabled: true, sortOrder: 9 },
    { id: 'laundry', name: '洗衣服务', currency: 'PHP', amount: 1200, billingRule: 'per-accommodation-period', periodWeeks: 4, rounding: 'proportional', includeInTotal: true, note: '每周2次洗衣服务；超过4周按实际周数比例预估。', enabled: true, sortOrder: 10 },
    { id: 'challenger-elective', name: 'Challenger特别选修课', currency: 'PHP', amount: 2000, billingRule: 'per-course-period', periodWeeks: 4, rounding: 'proportional', includeInTotal: true, note: '仅主动勾选Challenger特别选修课时计入。', enabled: true, sortOrder: 11 },
    { id: 'ielts-guarantee', name: 'IELTS保分班额外费用', currency: 'PHP', amount: 18000, billingRule: 'once', includeInTotal: true, note: '仅选择IELTS Guarantee时计入；保证条件需由顾问确认。', enabled: true, sortOrder: 12 },
    { id: 'room-deposit', name: '宿舍押金（可退）', currency: 'PHP', amount: 3000, billingRule: 'optional', includeInTotal: false, multiplyByStudents: true, note: JIC_LOCAL_FEE_COPY.deposit, enabled: true, sortOrder: 13 },
  ],
  quoteSettings: {
    registrationFee: JIC_REGISTRATION_FEE,
    futurePriceRegistrationStart: '',
    futurePriceArrivalStart: '',
    shortStayRatios: {},
    peakSeasonFeePerWeek: JIC_PEAK_FEE_PER_WEEK,
    peakSeasonRanges: [
      { id: 'jic-peak-2026', label: '2026暑期旺季', start: '2026-06-28', end: '2026-08-22', enabled: true },
    ],
    promotions: [
      {
        ...promotion('jic-registration', '注册费优惠', 'jic-registration', 0),
        description: '老学员返校、在校延长或12周及以上学生免收一次性注册费。',
        discountType: 'none',
        waiveRegistration: true,
        minimumCourseWeeks: 12,
      },
      {
        ...promotion('jic-off-season-2026', '2026下半年淡季住宿优惠', 'jic-off-season-2026', 1),
        description: JIC_PROMOTION_COPY.offSeason,
        discountValue: 150,
        incrementValue: 50,
        incrementWeeks: 4,
        newStudentsOnly: true,
        arrivalStart: '2026-08-23',
        arrivalEnd: '2027-01-09',
        appliesTo: 'accommodation',
        minimumAccommodationWeeks: 4,
      },
      {
        ...promotion('jic-off-season-2027-a', '2027上半年淡季住宿优惠', 'jic-off-season-2027', 2),
        description: JIC_PROMOTION_COPY.offSeason,
        discountValue: 100,
        incrementValue: 50,
        incrementWeeks: 4,
        newStudentsOnly: true,
        arrivalStart: '2027-02-21',
        arrivalEnd: '2027-06-26',
        appliesTo: 'accommodation',
        minimumAccommodationWeeks: 4,
      },
      {
        ...promotion('jic-off-season-2027-b', '2027下半年淡季住宿优惠', 'jic-off-season-2027', 3),
        description: JIC_PROMOTION_COPY.offSeason,
        discountValue: 100,
        incrementValue: 50,
        incrementWeeks: 4,
        newStudentsOnly: true,
        arrivalStart: '2027-08-22',
        arrivalEnd: '2028-01-08',
        appliesTo: 'accommodation',
        minimumAccommodationWeeks: 4,
      },
      {
        ...promotion('jic-long-term', '长期学习优惠', 'jic-long-term', 4),
        description: JIC_PROMOTION_COPY.longTerm,
        discountTiers: { '12': 300, '16': 400, '20': 500, '24': 600 },
        registrationStart: '2026-03-08',
        arrivalStart: '2026-03-08',
        minimumCourseWeeks: 12,
      },
      {
        ...promotion('jic-besa', 'BESA优惠', 'jic-besa', 5),
        description: JIC_PROMOTION_COPY.besa,
        incrementWeeks: 4,
        incrementValue: 100,
        registrationStart: '2026-04-01',
        registrationEnd: '2026-06-30',
        arrivalStart: '2026-08-23',
        arrivalEnd: '2026-12-13',
        newStudentsOnly: true,
      },
      ...[
        ['jic-holiday-2026-a', '2026圣诞优惠第一档', '2026-11-29', '2026-12-13', 200],
        ['jic-holiday-2026-b', '2026圣诞优惠第二档', '2026-12-27', '2027-01-10', 200],
        ['jic-holiday-2027-a', '2027圣诞优惠第一档', '2027-11-28', '2027-12-12', 150],
        ['jic-holiday-2027-b', '2027圣诞优惠第二档', '2027-12-26', '2028-01-09', 150],
      ].map(([id, name, start, end, amount], index) => ({
        ...promotion(String(id), String(name), 'jic-holiday', 6 + index),
        description: JIC_PROMOTION_COPY.holiday,
        discountValue: Number(amount),
        arrivalStart: String(start),
        arrivalEnd: String(end),
        eligibleRoomIds: twinAndQuadRoomIds,
        newStudentsOnly: true,
      })),
    ],
    localFeeIntro: JIC_LOCAL_FEE_COPY.intro,
    courseTableTitle: 'JIC 2026年课程费 / 4周',
    courseTableNote: 'Challenger与Premium课程分校区显示；课程与住宿最低4周，6周及更长按周数比例计算。',
    groupClassNote: 'Challenger偏ESL与IELTS强化，Premium偏口语、主题与职业英语；具体安排以所选课程说明为准。',
    roomTableTitle: 'JIC 2026年住宿费 / 4周',
    roomTableNote: 'Challenger与Premium房型不可跨校区混选；Premium 2027淡季单人房优惠仅适用于无阳台房型。',
    stayPolicyTitle: 'JIC入住与校区提醒',
    stayPolicies: [
      { label: '入住日期', value: '周日入住', note: '课程与住宿按完整周计算。' },
      { label: '退房日期', value: '周六退房', note: '延住及额外住宿需先确认空房和费用。' },
      { label: '双校区', value: 'Challenger / Premium', note: '每名学生须在同一校区选择课程和住宿。' },
    ],
    extraNightRates: [],
  },
  quoteImageSettings: {
    paymentSectionTitle: '学校费用明细',
    paymentNotes: { registration: '每名学生一次；符合条件时在优惠行抵扣', course: '', accommodation: '', promotion: '按当前日期、房型和周数自动核算' },
    localFeeSectionTitle: '到校后学杂费明细',
    localFeeIntro: '以下按当前签证、课程、住宿与接机选择预估；可退宿舍押金另列。',
    localFeeNotes: {},
    serviceSectionTitle: '为什么选择思达启航？',
    benefits: [
      { title: '0中介费', text: '学校合作价格，不额外加收服务费' },
      { title: '价格保护', text: '同条件可比价，核实更低价退差价' },
      { title: '全程报名协助', text: '选校、签证、付款及行前指导' },
      { title: '海外驻点售后', text: '学习期间持续跟进，问题有人协助' },
    ],
    serviceLocations: ['深圳总部', '菲律宾驻点', '欧洲驻点'],
    alumniBenefitTitle: 'JIC优惠提醒',
    alumniBenefitText: '淡季、长期、BESA与节日优惠按报名日、入学日、房型及周数自动核对；最终资格以学校确认为准。',
    noteSectionTitle: '报价说明',
    footerNotes: [
      '课程和住宿最低4周；周日入住、周六退房。',
      'Challenger与Premium的课程和住宿须按同一校区选择。',
      '人民币金额按生成当日参考汇率估算，最终以实际支付汇率为准。',
      '最终以学校价格、空房、优惠资格、移民局政策及顾问确认结果为准。',
    ],
  },
  media: [],
});

export const cloneJicContentConfig = (value: CiaContentConfig): CiaContentConfig => {
  const cloned = structuredClone(value);
  if (!cloned.quoteImageSettings.localFeeNotes) cloned.quoteImageSettings.localFeeNotes = {};
  if (!cloned.media) cloned.media = [];
  return cloned;
};
