// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XiaoJuanSchoolPayment.Server.Data;

#nullable disable

namespace XiaoJuanSchoolPayment.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250908185032_SetupSchoolDb")]
    partial class SetupSchoolDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolFees");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolLessons");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolNotes");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolRooms");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolFee", b =>
                {
                    b.HasOne("XiaoJuanSchoolPayment.Server.Data.Models.School", null)
                        .WithMany("SchoolFees")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolLesson", b =>
                {
                    b.HasOne("XiaoJuanSchoolPayment.Server.Data.Models.School", "School")
                        .WithMany("SchoolLessons")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolNote", b =>
                {
                    b.HasOne("XiaoJuanSchoolPayment.Server.Data.Models.School", null)
                        .WithMany("SchoolNotes")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.SchoolRoom", b =>
                {
                    b.HasOne("XiaoJuanSchoolPayment.Server.Data.Models.School", "School")
                        .WithMany("SchoolRooms")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("XiaoJuanSchoolPayment.Server.Data.Models.School", b =>
                {
                    b.Navigation("SchoolFees");

                    b.Navigation("SchoolLessons");

                    b.Navigation("SchoolNotes");

                    b.Navigation("SchoolRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
